# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import words_pb2 as words__pb2


class WordServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestWord = channel.unary_stream(
                '/WordService/RequestWord',
                request_serializer=words__pb2.WordRequest.SerializeToString,
                response_deserializer=words__pb2.WordReply.FromString,
                )


class WordServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WordServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestWord': grpc.unary_stream_rpc_method_handler(
                    servicer.RequestWord,
                    request_deserializer=words__pb2.WordRequest.FromString,
                    response_serializer=words__pb2.WordReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WordService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WordService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/WordService/RequestWord',
            words__pb2.WordRequest.SerializeToString,
            words__pb2.WordReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
