# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: words.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='words.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bwords.proto\"\x1b\n\x0bWordRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\tWordReply\x12\x0f\n\x07message\x18\x01 \x01(\t2:\n\x0bWordService\x12+\n\x0bRequestWord\x12\x0c.WordRequest\x1a\n.WordReply\"\x00\x30\x01\x62\x06proto3'
)




_WORDREQUEST = _descriptor.Descriptor(
  name='WordRequest',
  full_name='WordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='WordRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=42,
)


_WORDREPLY = _descriptor.Descriptor(
  name='WordReply',
  full_name='WordReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='WordReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['WordRequest'] = _WORDREQUEST
DESCRIPTOR.message_types_by_name['WordReply'] = _WORDREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WordRequest = _reflection.GeneratedProtocolMessageType('WordRequest', (_message.Message,), {
  'DESCRIPTOR' : _WORDREQUEST,
  '__module__' : 'words_pb2'
  # @@protoc_insertion_point(class_scope:WordRequest)
  })
_sym_db.RegisterMessage(WordRequest)

WordReply = _reflection.GeneratedProtocolMessageType('WordReply', (_message.Message,), {
  'DESCRIPTOR' : _WORDREPLY,
  '__module__' : 'words_pb2'
  # @@protoc_insertion_point(class_scope:WordReply)
  })
_sym_db.RegisterMessage(WordReply)



_WORDSERVICE = _descriptor.ServiceDescriptor(
  name='WordService',
  full_name='WordService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=74,
  serialized_end=132,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestWord',
    full_name='WordService.RequestWord',
    index=0,
    containing_service=None,
    input_type=_WORDREQUEST,
    output_type=_WORDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORDSERVICE)

DESCRIPTOR.services_by_name['WordService'] = _WORDSERVICE

# @@protoc_insertion_point(module_scope)
